### PR TITLE
Add Finamp details, add Android as supported OS

### PR DESCRIPTION
**Pull request by Extarys**

### CODE REVIEW

**Comment by Extarys** [comment]
Once/If this is merged, I'll add the lyrics column. I just saw the issue about it :/

**Comment by basings** [comment]
@Extarys do you know that ios and android have feature parity or did you assume it? I kept them separate because of that. But it would be great to reduce the table size and merge them together

**Comment by Extarys** [comment]
Oh :brain: Smart, I didn't think about that at all! I'll do some digging and get back at you :wink:

**Comment by basings** [comment]
@Extarys did you get further insights on this?

**Comment by Extarys** [comment]
I forgot :stuck_out_tongue: I made an issue to ask as I couldn't find any info on the web or in the repo's readme/issues.

**Comment by UnicornsOnLSD** [comment]
iOS and Android both have feature parity, see the response to the issue at https://github.com/UnicornsOnLSD/finamp/issues/154

**Comment by basings** [comment]
sweet! I somehow didn't see the comments until now. Thank you guys =)

**Pull request merged**
